version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: dreamhacker-admin
      POSTGRES_PASSWORD: thuan286
      POSTGRES_DB: dreamhacker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema/user.init.sql:/docker-entrypoint-initdb.d/user.init.sql
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
