version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: phamvant
      POSTGRES_PASSWORD: thuan286
      POSTGRES_DB: dreamhacker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema/01.user.init.sql:/docker-entrypoint-initdb.d/001.user.init.sql
      - ./database/schema/02.session.init.sql:/docker-entrypoint-initdb.d/002.session.init.sql
      - ./database/schema/03.program.init.sql:/docker-entrypoint-initdb.d/003.program.init.sql
      - ./database/schema/04.category.init.sql:/docker-entrypoint-initdb.d/004.category.init.sql
      - ./database/schema/05.post.init.sql:/docker-entrypoint-initdb.d/005.post.init.sql
      - ./database/schema/06.post_universal.init.sql:/docker-entrypoint-initdb.d/006.post_universal.init.sql
      - ./database/schema/07.comment.init.sql:/docker-entrypoint-initdb.d/007.comment.init.sql

      # - ./database/schema/mock/post.sql:/docker-entrypoint-initdb.d/post.sql
      # - ./database/schema/mock/post_universal.sql:/docker-entrypoint-initdb.d/post_universal.sql

      - ./database/trigger/01.update_total_post.sql:/docker-entrypoint-initdb.d/006.update_total_post.sql

    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
